version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}